blank_issues_enabled: false
contact_links:
  - name: Superboard Flight Deck
    url: https://github.com/users/Wladefant/projects/5
    about: Global Project 5 Flight Deck and Superboard system tracking
